### ISSUE TITLE
I have an Issue 

### ISSUE THREAD

**Issue by kaifsarkar123** [V-know/ChatGPT-Telegram-Bot#31]
![Screenshot_20231015_212017_Chrome](https://github.com/V-know/ChatGPT-Telegram-Bot/assets/139149350/e512715f-6b79-4421-bea7-071bdad1eb25)

**Comment by kaifsarkar123** [comment]
I thing the error is because I did not put the mysql information

**Comment by V-know** [comment]
It said you need to use a DB accoutn with 'SUPER privilege' to connect you database, AKA, your account permissions are insufficient.

**Comment by yesbhautik** [comment]
same error

**Comment by V-know** [comment]
Please make sure your account have the right  permission to connect the Database.

**Comment by V-know** [comment]
Hi @yesbhautik  and @kaifsarkar123 
The error come from this line [MySqlConn.py#L41C32-L41C68)](https://github.com/V-know/ChatGPT-Telegram-Bot/blob/bda9b5cbdec4495c25ce2f7826ac439fde993936/db/MySqlConn.py#L41C32-L41C68)  which I already coment it out in PR #34.

That option modify the db timze at the beginning of every session, and it require SUPER privilege.

Clone the newest code and try it again, enjoy!

**Comment by yesbhautik** [comment]
Yup, Please Close the issue
