### ISSUE TITLE
Worst Documentation, can you please update proper documentation

### ISSUE THREAD

**Issue by yesbhautik** [V-know/ChatGPT-Telegram-Bot#32]
I wasted my 5-6 Hours to connect DB, you maked the script Containerized. Then why its effecting pre installed stuff. Then i tried to create DB and user with pre install mysql, and filled at confing file. still giving a lot of error.
After wasting a lot of time, no results.

give proper option to use external DB or Mongo db URL. or make proper command so anyone can run your script

**Comment by V-know** [comment]
It seems you are bothed by the DB connection.

You can just use your own existed Database, or create a MySQL docker container  with [db/docker-compose.yaml](https://github.com/V-know/ChatGPT-Telegram-Bot/blob/main/db/docker-compose.yaml)

You can paste the error here, we can fix it together.

Or contect https://t.me/AiMessagerBot to talk with me directly.

**Comment by V-know** [comment]
Fixed in #34

**Comment by yesbhautik** [comment]
Thanks for Help @V-know. 😀
